- name: Assurer que /cloud1/ existe
  file:
    path: ./cloud1/
    state: directory
    mode: '0755'

- name: copy docker-compose
  copy:
    src: ./docker-compose.yml
    dest: ./cloud1
    mode: '0644'


- name: Synchronization of src on the control machine to dest on the remote hosts
  ansible.posix.synchronize:
    src: ./wordpress
    dest: ./cloud1

- name: Synchronization of src on the control machine to dest on the remote hosts
  ansible.posix.synchronize:
    src: ./mysql
    dest: ./cloud1

- name: Synchronization of src on the control machine to dest on the remote hosts
  ansible.posix.synchronize:
    src: ./nginx
    dest: ./cloud1

- name: Replace part of the line (substring) in the configuration file
  replace:
    path: ./cloud1/mysql/cloud1.sql
    regexp: "__cloud1_ec2_ip__"
    replace: "https://{{ cloud1_ec2_ip }}"

#name: Update WordPress site URL in MySQL (inside Docker)
#  community.mysql.mysql_query:
#    login_host: "mysql_cloud1"  # Nom du container MySQL
#    login_user: "root"
#    login_password: "root"
#    login_db: "wordpress_db"
#    query:
#      - "UPDATE wp_options SET option_value = 'https://{{ cloud1_ec2_ip }}' WHERE option_name = 'siteurl';"
#      - "UPDATE wp_options SET option_value = 'https://{{ cloud1_ec2_ip }}' WHERE option_name = 'home';"


- name: create and start services
  community.docker.docker_compose_v2:
    project_src: ./cloud1
  register: output