- name: Assurer que /cloud1/ existe
  file:
    path: ./cloud1/
    state: directory
    mode: '0755'

- name: copy docker-compose
  copy:
    src: ./docker-compose.yml
    dest: ./cloud1
    mode: '0644'

- name: Synchronization of src on the control machine to dest on the remote hosts
  ansible.posix.synchronize:
    src: ./wordpress
    dest: ./cloud1

- name: Synchronization of src on the control machine to dest on the remote hosts
  ansible.posix.synchronize:
    src: ./mysql
    dest: ./cloud1

- name: Synchronization of src on the control machine to dest on the remote hosts
  ansible.posix.synchronize:
    src: ./nginx
    dest: ./cloud1

- name: Recursively change ownership of a directory
  ansible.builtin.file:
    path: ./cloud1/wordpress/wp-content
    owner: www-data
    group: www-data
    mode: '0775'
    recurse: yes

- name: Replace part of the line (substring) in the configuration file
  replace:
    path: ./cloud1/mysql/cloud1.sql
    regexp: "__cloud1_ec2_ip__"
    replace: "https://{{ cloud1_ec2_ip }}"

- name: create and start services
  community.docker.docker_compose_v2:
    project_src: ./cloud1
  register: output
